name: SetNameColor
version: v1.1
main: dmvmc.setNameColor.SetNameColor
api-version: "1.21"
description: A plugin that allows players to set their name color in chat

commands:
  setnamecolor:
    description: Sets the color of your name in chat
    usage: /setnamecolor <color|#rrggbb> [playerName]
    permission: setnamecolor.set

permissions:
  setnamecolor.set:
    description: Allows the player to set their name color
    default: true

  setnamecolor.setOther:
    description: Allows the player to set other players name color
    default: op